'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace YourNamespace

    Partial Public Class Signup

        '''<summary>
        '''signupForm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents signupForm As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''uName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents uName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''uNameError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents uNameError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lNameError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lNameError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''fName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''fNameError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fNameError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''email control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents email As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''emailError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents emailError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''gender control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gender As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''genderError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents genderError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''prefix control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents prefix As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''phone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phone As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''phoneError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phoneError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''yearBorn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents yearBorn As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''yearBornError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents yearBornError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''city control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents city As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''cityError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cityError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''hobbies control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hobbies As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''hobbiesError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hobbiesError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pw control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pw As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''pwError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pwError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pwConfirm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pwConfirm As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''pwConfirmError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pwConfirmError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnSubmit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
